# -*- coding: utf-8 -*-
"""create_navi_answer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZXCSqJ7oM1kMvB3xszES0E6pgv9OKBR7


import random

class create_navi_answer:
    def __init__(self, start, end):
        self.my_list = nav_que[start: end]

    def first_sent(self):
        nav_first = []
        while True:
            temp = str(input('첫마디set:            [끝내시려면 "-1"]\n'))
            if temp == '-1':
                break
            temp = temp+'\n'
            nav_first.append(temp)

        return nav_first
    
    def create_answer(self, first_sentence, sentence_name): # sentence_naem == 구분하기 위한 str 문구
        temp_list = []
        while True:
            temp = str(input(f'{sentence_name}:             [끝내시려면 "-1"]\n'))
            if temp == '-1':
                break
            
            rannum = random.randrange(1, len(first_sentence))
            temp = first_sentence[rannum] + temp
            temp_list.append(temp)

        return temp_list

